### ISSUE TITLE
'One Little Ghost' .p file crashes on load

### ISSUE THREAD

**Issue by patters-match** [holmatic/zx-iot-mi#1]
Hi holmatic,

Firstly thanks so much for this project! It's the most impressive electronics project I have ever put together. I wrote up my build experiences over at [SinclairZXWorld](https://www.sinclairzxworld.com/viewtopic.php?f=7&t=4155) .

I'm running version 0.2.2.0, updated via OTA method after the initial flash of the ESP32. The ZX-WESPI will load everything I've tried so far except the game [One Little Ghost](https://bobs-stuff.itch.io/one-little-ghost) which seems to crash with no video output as it loads. Can you confirm whether this happens for you? I have tested that the exact same file plays with no issue on my choice of emulator - [Clock Signal for MacOS](https://github.com/TomHarte/CLK), and it also loads fine on my ZX81 using a MaxDuino device.

Is there a way you can debug why this .p file in particular may not work? Bob Smith, the game's author, [has mentioned](https://www.sinclairzxworld.com/viewtopic.php?p=42464#p42464) that he didn't do anything differently with this game's .p file as compared to his many others.

Thanks!

**Comment by holmatic** [comment]
Hi patters,

thanks for the message, happy that the project in most cases works out for you. The quickloader is located near the stack space, maybe there is the problem.

On a quick check on my system I was able to successfully run "One Little Ghost", however I have some nonstandard hardware with 56K RAM, and also a development version of the ZX-WESPI. Need to see what makes the difference.

**Comment by patters-match** [comment]
https://sinclairzxworld.com/viewtopic.php?p=49947#p49947

It turns out the filename was too long. That's all it was!
